#!/usr/bin/env python3
"""
Calibration script to discover the relationship between LCA_5 signals and steering angle.

Modes:
  1. scale (default): Test if DBC scale is correct by commanding sub-degree angles
  2. single: Test LCA_5_STEER only (legacy integer values)
  3. discover: Test old 2-byte encoding scheme

Usage:
  python calibrate_angle_factor.py              # Scale verification mode
  python calibrate_angle_factor.py --single     # Single byte mode (legacy)
  python calibrate_angle_factor.py --discover   # Discovery mode (legacy)

Requirements:
  - openpilot must be running (carState must be published)
  - Car should be stationary or moving slowly
  - Steering must be free to move (not held by driver)
"""

import sys
import time
import signal
import argparse
import statistics
from pathlib import Path

# Add openpilot to path if needed
OPENPILOT_PATH = Path(__file__).resolve().parents[5]
if str(OPENPILOT_PATH) not in sys.path:
  sys.path.insert(0, str(OPENPILOT_PATH))

import cereal.messaging as messaging

# Configuration
LIVE_TESTING_FILE = "/data/openpilot/live_testing.txt"
LOG_FILE = "/data/openpilot/angle_calibration.csv"

# Settling detection parameters
SETTLE_THRESHOLD_DEG = 0.15  # Angle must be stable within this range
SETTLE_WINDOW = 15           # Number of samples to check for stability
SETTLE_TIMEOUT_S = 5.0       # Max time to wait for settling
SAMPLE_INTERVAL_S = 0.05     # 50ms between samples (20Hz)

# Final sampling after settling
FINAL_SAMPLE_COUNT = 20      # Number of samples to average for final reading

# Safety limits
MAX_ANGLE_DEG = 40.0         # Stop if angle exceeds this


class SteeringCalibrator:
  def __init__(self, max_angle: float):
    self.max_angle = max_angle
    self.results = []  # List of (turn_bits, steer, avg_angle, std_angle) tuples
    self.running = True
    self.sm = None

    signal.signal(signal.SIGINT, self._signal_handler)
    signal.signal(signal.SIGTERM, self._signal_handler)

  def _signal_handler(self, sig, frame):
    print("\nInterrupted, cleaning up...")
    self.running = False
    self._disable_live_testing()
    sys.exit(0)

  def _write_live_testing(self, turn_bits: int | None, steer: float | None):
    """Write test configuration to live_testing.txt"""
    lines = ["# Auto-generated by calibrate_angle_factor.py", "lat_active=True"]
    if turn_bits is not None:
      lines.append(f"lca_5.lca_turn_bits={turn_bits}")
    if steer is not None:
      # Support float values for sub-degree testing
      lines.append(f"lca_5.lca_5_steer={steer}")

    with open(LIVE_TESTING_FILE, 'w') as f:
      f.write('\n'.join(lines) + '\n')

  def _disable_live_testing(self):
    """Disable live testing"""
    with open(LIVE_TESTING_FILE, 'w') as f:
      f.write("# Auto-generated\nlat_active=False\n")
    print("Live testing disabled")

  def _get_angle(self) -> float | None:
    """Get current steering angle from carState"""
    self.sm.update(timeout=1000)
    if self.sm.updated['carState']:
      return self.sm['carState'].steeringAngleDeg
    return None

  def _wait_for_settle(self) -> bool:
    """Wait until steering angle stabilizes"""
    recent_angles = []
    start_time = time.time()

    while self.running:
      if time.time() - start_time > SETTLE_TIMEOUT_S:
        print(f"  WARNING: Settle timeout after {SETTLE_TIMEOUT_S}s")
        return False

      angle = self._get_angle()
      if angle is None:
        continue

      recent_angles.append(angle)
      if len(recent_angles) > SETTLE_WINDOW:
        recent_angles.pop(0)

      if len(recent_angles) >= SETTLE_WINDOW:
        angle_range = max(recent_angles) - min(recent_angles)
        if angle_range < SETTLE_THRESHOLD_DEG:
          elapsed = time.time() - start_time
          print(f"  Settled in {elapsed:.2f}s (range: {angle_range:.3f}°)")
          return True

      time.sleep(SAMPLE_INTERVAL_S)

    return False

  def _collect_samples(self, count: int) -> list[float]:
    """Collect steering angle samples"""
    samples = []
    for _ in range(count):
      if not self.running:
        break
      angle = self._get_angle()
      if angle is not None:
        samples.append(angle)
      time.sleep(SAMPLE_INTERVAL_S)
    return samples

  def _test_point(self, turn_bits: int | None, steer: float | None, log_file) -> tuple[float, float] | None:
    """Test a single (turn_bits, steer) combination"""
    tb_str = str(turn_bits) if turn_bits is not None else "stock"
    st_str = f"{steer:.3f}" if steer is not None else "stock"
    print(f"  Testing LCA_TURN_BITS={tb_str}, LCA_5_STEER={st_str}")

    self._write_live_testing(turn_bits, steer)

    print(f"    Waiting for settle...")
    if not self._wait_for_settle():
      return None

    # Safety check
    current_angle = self._get_angle()
    if current_angle is not None and abs(current_angle) > self.max_angle:
      print(f"    SAFETY: Angle {current_angle:.1f}° exceeds limit!")
      return None

    print(f"    Collecting samples...")
    samples = self._collect_samples(FINAL_SAMPLE_COUNT)

    if len(samples) < 3:
      print(f"    WARNING: Only {len(samples)} samples")
      return None

    avg_angle = statistics.mean(samples)
    std_angle = statistics.stdev(samples) if len(samples) > 1 else 0

    # Log to file
    timestamp = time.time()
    for i, angle in enumerate(samples):
      log_file.write(f"{timestamp},{turn_bits},{steer},{angle:.4f},{i}\n")
    log_file.flush()

    print(f"    Result: {avg_angle:.3f}° (±{std_angle:.3f}°)")
    return (avg_angle, std_angle)

  def connect(self) -> bool:
    """Connect to carState"""
    print("Connecting to carState...")
    self.sm = messaging.SubMaster(['carState'])

    print("Waiting for messages...")
    for _ in range(50):
      self.sm.update(timeout=100)
      if self.sm.updated['carState']:
        print(f"Connected! Initial angle: {self.sm['carState'].steeringAngleDeg:.2f}°")
        return True
      time.sleep(0.1)

    print("ERROR: No carState messages. Is openpilot running?")
    return False

  def run_scale_mode(self):
    """Test sub-degree angles to verify DBC scale factor.

    If DBC scale (0.05596) is correct:
      - Commanded 0.5° should produce actual ~0.5°
      - Commanded 1.0° should produce actual ~1.0°

    If DBC scale is wrong (should be 1.0):
      - Commanded 0.5° would produce actual ~9° (packer sends raw=9)
      - Commanded 1.0° would produce actual ~18°
    """
    if not self.connect():
      return

    # Test sub-degree increments from a base angle
    # Going 10° → 10.1° → 10.2° tests if we can detect small changes
    test_values = [
      0.0,     # Neutral baseline
      # Test fine increments around 10° left
      10.0,
      10.1,
      10.2,
      10.5,
      11.0,
      10.0,    # Back to 10° to verify repeatability
      # Test fine increments around 10° right
      -10.0,
      -10.1,
      -10.2,
      -10.5,
      -11.0,
      -10.0,   # Back to -10°
      # Also test small angles from zero
      0.0,
      0.5,
      1.0,
      0.0,
      -0.5,
      -1.0,
      0.0,     # Back to neutral
    ]

    print(f"\n{'='*60}")
    print("SCALE VERIFICATION MODE")
    print(f"{'='*60}")
    print("Testing if DBC scale (0.05596 deg/count) is correct.")
    print("Commanding sub-degree angles and measuring actual response.")
    print()
    print("If correct: Commanded ≈ Actual")
    print("If wrong:   Commanded 0.5° → Actual ~9°")
    print(f"\nTest values: {test_values}")
    print(f"Safety limit: ±{self.max_angle}°\n")

    with open(LOG_FILE, 'w') as log:
      log.write("timestamp,commanded_deg,actual_deg,error_deg,sample_num\n")

      for i, commanded in enumerate(test_values):
        if not self.running:
          break
        print(f"\n[{i+1}/{len(test_values)}] Commanding: {commanded:.1f}°")
        result = self._test_point_scale(commanded, log)
        if result:
          self.results.append((commanded, result[0], result[1]))

    # Return to neutral
    print("\nReturning to neutral...")
    self._write_live_testing(None, 0.0)
    self._wait_for_settle()
    self._disable_live_testing()

    self._analyze_scale_mode()

  def _test_point_scale(self, commanded_deg: float, log_file) -> tuple[float, float] | None:
    """Test a single commanded angle (in degrees)"""
    print(f"  Commanding LCA_5_STEER = {commanded_deg:.3f}°")

    self._write_live_testing(None, commanded_deg)

    print(f"    Waiting for settle...")
    if not self._wait_for_settle():
      return None

    # Safety check
    current_angle = self._get_angle()
    if current_angle is not None and abs(current_angle) > self.max_angle:
      print(f"    SAFETY: Angle {current_angle:.1f}° exceeds limit!")
      return None

    print(f"    Collecting samples...")
    samples = self._collect_samples(FINAL_SAMPLE_COUNT)

    if len(samples) < 3:
      print(f"    WARNING: Only {len(samples)} samples")
      return None

    avg_angle = statistics.mean(samples)
    std_angle = statistics.stdev(samples) if len(samples) > 1 else 0

    # Log to file
    timestamp = time.time()
    for i, angle in enumerate(samples):
      error = angle - commanded_deg
      log_file.write(f"{timestamp},{commanded_deg:.4f},{angle:.4f},{error:.4f},{i}\n")
    log_file.flush()

    error = avg_angle - commanded_deg
    print(f"    Result: {avg_angle:.3f}° (error: {error:+.3f}°, std: ±{std_angle:.3f}°)")
    return (avg_angle, std_angle)

  def _analyze_scale_mode(self):
    """Analyze scale verification results"""
    if len(self.results) < 2:
      print("\nERROR: Not enough data")
      return

    print(f"\n{'='*60}")
    print("RESULTS: DBC Scale Verification")
    print(f"{'='*60}")

    print(f"\n{'Commanded':>12} {'Actual':>10} {'Error':>10} {'Std':>8}")
    print("-" * 45)
    for commanded, actual, std in self.results:
      error = actual - commanded
      print(f"{commanded:>12.3f} {actual:>10.3f} {error:>+10.3f} {std:>8.3f}")

    # Calculate metrics
    errors = [r[1] - r[0] for r in self.results]
    abs_errors = [abs(e) for e in errors]
    mean_abs_error = statistics.mean(abs_errors)
    max_abs_error = max(abs_errors)

    # Calculate ratio (actual/commanded) for non-zero commanded values
    ratios = []
    for commanded, actual, _ in self.results:
      if abs(commanded) > 0.05:  # Avoid division by near-zero
        ratios.append(actual / commanded)

    print(f"\n{'Analysis':^45}")
    print("-" * 45)
    print(f"Mean absolute error: {mean_abs_error:.3f}°")
    print(f"Max absolute error:  {max_abs_error:.3f}°")

    if ratios:
      mean_ratio = statistics.mean(ratios)
      print(f"Mean ratio (actual/commanded): {mean_ratio:.3f}")

      if 0.8 < mean_ratio < 1.2 and mean_abs_error < 1.0:
        print("\n✓ DBC SCALE IS CORRECT!")
        print("  Fine-grained control (~0.056°/count) is working.")
      elif mean_ratio > 10:
        print("\n✗ DBC SCALE IS WRONG!")
        print(f"  Actual ratio ~{mean_ratio:.0f}x means scale should be ~1.0, not 0.05596")
        print("  The packer is sending raw values that are too large.")
      else:
        print(f"\n? INCONCLUSIVE - ratio={mean_ratio:.2f}, error={mean_abs_error:.2f}°")
        print("  Check the raw data for more insight.")

    print(f"\nLog saved to: {LOG_FILE}")

  def run_single_mode(self):
    """Test LCA_5_STEER only (stock LCA_TURN_BITS) - legacy integer mode"""
    if not self.connect():
      return

    test_values = [0, 5, 10, 15, 20, 25, 30, 0, -5, -10, -15, -20, -25, -30, 0]

    print(f"\n{'='*60}")
    print("SINGLE BYTE MODE: Testing LCA_5_STEER with stock LCA_TURN_BITS")
    print(f"{'='*60}")
    print(f"Test values: {test_values}")
    print(f"Safety limit: ±{self.max_angle}°\n")

    with open(LOG_FILE, 'w') as log:
      log.write("timestamp,lca_turn_bits,lca_5_steer,angle_deg,sample_num\n")

      for i, steer in enumerate(test_values):
        if not self.running:
          break
        print(f"\n[{i+1}/{len(test_values)}]")
        result = self._test_point(None, steer, log)
        if result:
          self.results.append((None, steer, result[0], result[1]))

    # Return to neutral
    print("\nReturning to neutral...")
    self._write_live_testing(None, 0)
    self._wait_for_settle()
    self._disable_live_testing()

    self._analyze_single_mode()

  def run_discovery_mode(self):
    """Discover the relationship between both bytes"""
    if not self.connect():
      return

    # Test combinations to understand the 2D relationship
    # First, find what stock LCA_TURN_BITS is
    # Then test various combinations

    # Test old encoding scheme values
    # Old encoder: for angle >= 0, lca_turn_bits=128, lca_5_steer = angle/0.05596
    # For angle < 0, lca_turn_bits=255, lca_5_steer = 255 - abs(angle)/0.05596
    #
    # Test points (target_angle -> expected LCA_TURN_BITS, LCA_5_STEER):
    #   0.5° left  -> 128, 9
    #   1.0° left  -> 128, 18
    #   5.0° left  -> 128, 89
    #   10.0° left -> 128, 179
    #   0.5° right -> 255, 246
    #   1.0° right -> 255, 237
    #   5.0° right -> 255, 166
    #   10.0° right -> 255, 76

    test_points = [
      # (LCA_TURN_BITS, LCA_5_STEER, expected_angle_if_old_encoding_works)
      (128, 0, 0),
      (128, 9, 0.5),      # 0.5° left
      (128, 18, 1.0),     # 1.0° left
      (128, 45, 2.5),     # 2.5° left
      (128, 89, 5.0),     # 5.0° left
      (128, 179, 10.0),   # 10.0° left
      (255, 255, 0),      # 0° (right zero point)
      (255, 246, -0.5),   # 0.5° right
      (255, 237, -1.0),   # 1.0° right
      (255, 210, -2.5),   # 2.5° right
      (255, 166, -5.0),   # 5.0° right
      (255, 76, -10.0),   # 10.0° right
    ]

    turn_bits_values = None  # Signal to use test_points instead
    steer_values = None

    print(f"\n{'='*60}")
    print("DISCOVERY MODE: Testing OLD ENCODING scheme values")
    print(f"{'='*60}")
    print("Testing if old 2-byte encoding produces expected angles:")
    print("  Old scheme: counts = angle / 0.05596")
    print("  LEFT:  LCA_TURN_BITS=128, LCA_5_STEER=counts")
    print("  RIGHT: LCA_TURN_BITS=255, LCA_5_STEER=255-counts")
    print(f"Safety limit: ±{self.max_angle}°\n")

    total_tests = len(test_points)
    test_num = 0

    with open(LOG_FILE, 'w') as log:
      log.write("timestamp,lca_turn_bits,lca_5_steer,expected_angle,actual_angle,sample_num\n")

      for turn_bits, steer, expected_angle in test_points:
        if not self.running:
          break
        test_num += 1
        print(f"\n[{test_num}/{total_tests}] Expected: {expected_angle}°")
        result = self._test_point(turn_bits, steer, log)
        if result:
          self.results.append((turn_bits, steer, expected_angle, result[0], result[1]))

    # Return to neutral
    print("\nReturning to neutral...")
    self._write_live_testing(128, 0)  # Left zero point
    self._wait_for_settle()
    self._disable_live_testing()

    self._analyze_discovery_mode()

  def _analyze_single_mode(self):
    """Analyze single byte mode results"""
    if len(self.results) < 2:
      print("\nERROR: Not enough data")
      return

    print(f"\n{'='*60}")
    print("RESULTS: LCA_5_STEER → Steering Angle")
    print(f"{'='*60}")

    print(f"\n{'LCA_5_STEER':>12} {'Angle':>10} {'Std':>8}")
    print("-" * 35)
    for _, steer, angle, std in self.results:
      print(f"{steer:>12} {angle:>10.3f} {std:>8.3f}")

    # Linear regression
    steer_vals = [r[1] for r in self.results]
    angles = [r[2] for r in self.results]

    steer_mean = statistics.mean(steer_vals)
    angle_mean = statistics.mean(angles)

    num = sum((s - steer_mean) * (a - angle_mean) for s, a in zip(steer_vals, angles))
    den = sum((s - steer_mean) ** 2 for s in steer_vals)

    if abs(den) > 1e-10:
      slope = num / den
      intercept = angle_mean - slope * steer_mean
      print(f"\nLinear fit: angle = {slope:.4f} * LCA_5_STEER + {intercept:.3f}")
      print(f"(1 raw unit ≈ {slope:.3f}°)")

    print(f"\nLog saved to: {LOG_FILE}")

  def _analyze_discovery_mode(self):
    """Analyze discovery mode results"""
    if len(self.results) < 2:
      print("\nERROR: Not enough data")
      return

    print(f"\n{'='*60}")
    print("RESULTS: Old Encoding Test")
    print(f"{'='*60}")
    print("\nIf old encoding works: Expected ≈ Actual")
    print("If 1:1 mapping: Actual ≈ LCA_5_STEER (for TB=128) or 255-LCA_5_STEER (for TB=255)\n")

    print(f"{'TB':>4} {'Steer':>6} {'Expected':>10} {'Actual':>10} {'Error':>8} {'Std':>6}")
    print("-" * 50)

    for turn_bits, steer, expected, actual, std in self.results:
      error = actual - expected
      print(f"{turn_bits:>4} {steer:>6} {expected:>10.2f} {actual:>10.3f} {error:>+8.3f} {std:>6.3f}")

    # Check if old encoding works (errors should be small)
    errors = [abs(r[3] - r[2]) for r in self.results]
    mean_error = statistics.mean(errors)
    max_error = max(errors)

    print(f"\n{'Analysis':^50}")
    print("-" * 50)
    print(f"Mean absolute error: {mean_error:.3f}°")
    print(f"Max absolute error:  {max_error:.3f}°")

    if max_error < 1.0:
      print("\n✓ OLD ENCODING WORKS! Fine-grained control is possible.")
      print("  Resolution: ~0.056° per count")
    else:
      print("\n✗ Old encoding does NOT produce expected angles.")
      print("  The 2-byte encoding theory may be incorrect.")

    print(f"\nLog saved to: {LOG_FILE}")


def main():
  parser = argparse.ArgumentParser(description='Verify LCA_5 steering signal scale factor')
  parser.add_argument('--single', action='store_true',
                      help='Legacy mode: test integer LCA_5_STEER values')
  parser.add_argument('--discover', action='store_true',
                      help='Legacy mode: test old 2-byte encoding scheme')
  parser.add_argument('--max-angle', type=float, default=MAX_ANGLE_DEG,
                      help=f'Safety limit (default: {MAX_ANGLE_DEG}°)')
  args = parser.parse_args()

  print("=" * 60)
  print("LCA_5 Steering Scale Verification")
  print("=" * 60)
  print()
  print("IMPORTANT:")
  print("  1. openpilot must be running")
  print("  2. Car should be stationary or moving slowly")
  print("  3. Don't touch the steering wheel")
  print()
  input("Press Enter to start...")

  calibrator = SteeringCalibrator(args.max_angle)

  if args.single:
    calibrator.run_single_mode()
  elif args.discover:
    calibrator.run_discovery_mode()
  else:
    calibrator.run_scale_mode()


if __name__ == "__main__":
  main()
