#!/bin/bash
# Debug commands to run on Comma 3

echo "Run these commands on your Comma 3 after SSH:"
echo ""
echo "1. Check for Python errors in the logs:"
echo "grep -i 'error\|exception\|traceback' /data/log/swaglog.* | tail -30"
echo ""
echo "2. Check if car is detected:"
echo "grep -i 'fingerprint\|polestar' /data/log/swaglog.* | tail -20"
echo ""
echo "3. Check card.py output directly:"
echo "cd /data/openpilot && python3 selfdrive/car/card.py"
echo ""
echo "4. Check if CarParams is being created:"
echo "cat /data/params/d/CarParams | xxd | head -20"
echo ""
echo "5. Watch real-time logs:"
echo "tmux attach -t comma"
echo ""
echo "6. Check for missing modules:"
echo "cd /data/openpilot && python3 -c 'from selfdrive.car.volvo.interface import CarInterface; print(\"Interface loads OK\")'"
echo ""
echo "Please run command #1 and #3 first and share the output!"